version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your-openai-api-key-here}
    volumes:
      - ./backend:/app
      - sqlite_data:/app/data
    restart: unless-stopped

volumes:
  sqlite_data:
